version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345
    ports:
      - "90:80"
    depends_on:
      - db
   
volumes:
  persistent:
