version: "3.8"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    image: pgn123/web:33.0  # Specify the custom image name
    volumes:
      - ./bookdeck1:/var/www/html
    ports:
      - 80:80
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    image: pgn123/database:33.0  # Specify the custom image name
    container_name: docker-db-1 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "90:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345

volumes:
  db_data:
