version: "3.8"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/var/www/html
    ports:
      - 80:80
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: docker-db-1 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - db_data1:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "90:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345

volumes:
  db_data1:
