FROM php:7.4-apache
COPY web/ /var/www/html/
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-enable mysqli
EXPOSE 80
